### ISSUE TITLE
有关训练时的报错问题tensorflow.python.framework.errors_impl.OutOfRangeError

### ISSUE THREAD

**Issue by marshmallow1412** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#15]
您好，想请教一下想使用您的代码尝试运行您提供的数据集，是将下载的所有xml文件放入pcb/Annotations，图片文件放入pcb/JPEGImages，然后将pcb文件夹放在$PATH_ROOT/data中么？在经过divide_data和conver_data_to_tfrecord之后，在运行train.py文件时，我遇到了这样的报错，请问您知道原因么？期待您的回答，谢谢！

> Traceback (most recent call last):
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[{{node get_batch/batch}}]]
  (1) Out of range: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[{{node get_batch/batch}}]]
         [[sample_anchors_minibatch/PyFunc/_1605]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 194, in <module>
    train()
  File "train.py", line 170, in train
    _, global_stepnp, summary_str = sess.run([train_op, global_step, summary_op])
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[node get_batch/batch (defined at ../data/io/read_tfrecord.py:98) ]]
  (1) Out of range: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[node get_batch/batch (defined at ../data/io/read_tfrecord.py:98) ]]
         [[sample_anchors_minibatch/PyFunc/_1605]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'get_batch/batch':
  File "train.py", line 194, in <module>
    train()
  File "train.py", line 34, in train
    is_training=True)
  File "../data/io/read_tfrecord.py", line 98, in next_batch
    dynamic_pad=True)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/training/input.py", line 1021, in batch
    name=name)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/training/input.py", line 790, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3862, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/lkc/.virtualenvs/tensor_gpu/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by xl123321** [comment]
请问问题解决了吗？

**Comment by Ixiaohuihuihui** [comment]
如果已经解决的话，我将关闭这个issue.
