### ISSUE TITLE
Cannot Run inference

### ISSUE THREAD

**Issue by anyin233** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#48]
我根据Readme进行，使用单张图片进行了inference，出现了如下错误

tensorflow version: 1.13.1
Traceback:
```
Traceback (most recent call last):
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Missing 1-th output from {{node Fast-RCNN/rois_pooling/ROI_Warping_P5/MaxPool2D/MaxPool}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jizm/Tiny-Defect-Detection-for-PCB-master/tools/inference.py", line 121, in <module>
    inference_save_path=args.save_dir)
  File "/home/jizm/Tiny-Defect-Detection-for-PCB-master/tools/inference.py", line 90, in inference
    detect(det_net=faster_rcnn, inference_save_path=inference_save_path, real_test_imgname_list=test_imgname_list)
  File "/home/jizm/Tiny-Defect-Detection-for-PCB-master/tools/inference.py", line 60, in detect
    feed_dict={img_plac: raw_img[:, :, ::-1]}  # cv is BGR. But need RGB
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1347, in _do_call
    message = error_interpolation.interpolate(message, self._graph)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/framework/error_interpolation.py", line 294, in interpolate
    field_dict = compute_field_dict(op)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/framework/error_interpolation.py", line 249, in compute_field_dict
    frame = _get_defining_frame_from_op(op)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/framework/error_interpolation.py", line 212, in _get_defining_frame_from_op
    frame_index = _find_index_of_defining_frame_for_op(op)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/framework/error_interpolation.py", line 198, in _find_index_of_defining_frame_for_op
    tf_traceback = tf_stack.convert_stack(op._traceback)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/site-packages/tensorflow/python/util/tf_stack.py", line 94, in convert_stack
    line = linecache.getline(filename, lineno, frame_globals)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/home/jizm/anaconda3/envs/bishe/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 5561-5562: invalid continuation byte
```

**Comment by Ixiaohuihuihui** [comment]
环境有问题。
