### ISSUE TITLE
Make tfrecord

### ISSUE THREAD

**Issue by qq364817579** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#52]
Traceback (most recent call last):
  File "convert_data_to_tfrecord.py", line 123, in <module>
    convert_pascal_to_tfrecord()
  File "convert_data_to_tfrecord.py", line 102, in convert_pascal_to_tfrecord
    'img_name': _bytes_feature(img_name),
  File "convert_data_to_tfrecord.py", line 29, in _bytes_feature
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))
TypeError: 'rotation_90_light_01_spur_05_2_600.jpg' has type str, but expected one of: bytes

训练过程运行convert_data_to_tfrecord.py报错此图片(rotation_90_light_01_spur_05_2_600.jpg)类型不符合   在这之前我按照0.8的比列运行了divide_data.py成功得到了pcb_train和pcb_test文件夹      还望高手过目看看此类问题如何解决。

**Comment by zhagao12138** [comment]
您好我也遇到了一样的问题，请问您是如何解决的？

**Comment by qq364817579** [comment]
> 您好我也遇到了同样的问题，请问您是如何解决的？

大概率是环境配置的问题，过去太久了我也忘记具体怎么解决的了。
