### ISSUE TITLE
Enviroments issue

### ISSUE THREAD

**Issue by dream952118** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#54]
感谢你们的贡献我有以下问题，
环境确实已经按照Readme安装且tensorflow也装过1.12 或是1.15都还是不行，
可以解答吗~?谢谢你们

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 194, in <module>
    train()
  File "train.py", line 133, in train
    restorer.restore(sess, restore_ckpt)
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1378, in _do_call
    message = error_interpolation.interpolate(message, self._graph)
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/site-packages/tensorflow_core/python/framework/error_interpolation.py", line 454, in interpolate
    common_prefix = traceback_files_common_prefix(tagged_ops)
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/site-packages/tensorflow_core/python/framework/error_interpolation.py", line 358, in traceback_files_common_prefix
    for frame in op.traceback:
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 2309, in traceback
    return tf_stack.convert_stack(self._traceback)
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/site-packages/tensorflow_core/python/util/tf_stack.py", line 199, in convert_stack
    return tuple(_tuple_generator())
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/site-packages/tensorflow_core/python/util/tf_stack.py", line 189, in _tuple_generator
    line = linecache.getline(filename, lineno, frame.globals)
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/home/avaryholding/anaconda3/envs/tdd/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 5561-5562: invalid continuation byte

**Comment by Ixiaohuihuihui** [comment]
这看着不像tesnforflow的问题，不过你这问题其他人也有遇到过吧，'utf-8'编码的问题，谷歌搜一下，应该可以很快解决

**Comment by dream952118** [comment]
谢谢您的答覆，我再试着解决看看。

**Comment by mycccc0821** [comment]
> 谢谢您的答覆，我再试着解决看看。

你好！请问你解决了嘛，我也遇到了这样的问题没有Google正确的适用于这个项目的解决方式
