### ISSUE TITLE
cannot get the correct results when run the inference.py

### ISSUE THREAD

**Issue by jiehui87** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#8]
Traceback (most recent call last):
  File "inference.py", line 17, in <module>
    from libs.networks import build_whole_network
  File "../libs/networks/build_whole_network.py", line 7, in <module>
    import tensorflow.contrib.slim as slim
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 22, in <module>
    from tensorflow.contrib import batching
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/batching/__init__.py", line 23, in <module>
    from tensorflow.contrib.batching.python.ops.batch_ops import batch_function
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/batching/python/ops/batch_ops.py", line 29, in <module>
    @ops.RegisterGradient("Batch")
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2329, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 67, in register
    stack = traceback.extract_stack()
  File "/usr/lib64/python3.6/traceback.py", line 207, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/usr/lib64/python3.6/traceback.py", line 358, in extract
    f.line
  File "/usr/lib64/python3.6/traceback.py", line 282, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/usr/lib64/python3.6/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib64/python3.6/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib64/python3.6/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 5561-5562: invalid continuation byte

**Comment by Ixiaohuihuihui** [comment]
Sorry, I think it is not a code bug. You can just search solutions in Google.

**Comment by antonia329** [comment]
Same question. Do you know how to fix it? Thank you.

**Comment by zhagao12138** [comment]
Same question. Do you know how to fix it? Thank you. -.-
